export interface Project {
  id: string;
  title: string;
  tagline: string;
  category: "logo" | "poster" | "branding" | "website" | "social-media";
  categoryLabel: string;
  client: string;
  year: string;
  image: string;
  featured?: boolean;
  metrics: string;
  description: string;
  deliverables: string[];
  tools: string[];
  liveUrl?: string;
}

export const CATEGORIES = [
  { id: "all", label: "All Projects" },
  { id: "logo", label: "Logo" },
  { id: "poster", label: "Poster" },
  { id: "branding", label: "Branding" },
  { id: "website", label: "Website" },
  { id: "social-media", label: "Social Media" },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];

export const PROJECTS: Project[] = [
  // ==========================================
  // --- 1. LOGO CATEGORY ---
  // ==========================================
  {
    id: "dryvex-carwash-logo",
    title: "Dryvex Car Wash Emblem",
    tagline: "Automotive Geometric Monogram & Exterior Signage",
    category: "logo",
    categoryLabel: "Logo Design",
    client: "Dryvex Car Wash",
    year: "2025",
    image: "/Portfolio_page-0004.jpg",
    featured: true,
    metrics: "Deployed across multiple car care centers & 3D signage",
    description: "Designed a high-impact geometric automotive emblem combining speed dynamics and precision car care. Adapted for illuminated outdoor fascia signage, high-pressure equipment, and premium customer service touchpoints.",
    deliverables: ["Vector Master Logo", "Outdoor Signage Specs", "Monochrome Variants", "Icon Grid Standards"],
    tools: ["Adobe Illustrator", "Photoshop", "CorelDraw"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20am%20interested%20in%20a%20logo%20design%20like%20Dryvex%20Carwash",
  },
  {
    id: "hijra-dates-nuts-logo",
    title: "Hijra Dates & Nuts",
    tagline: "Heritage Palm Crest Mark & Retail Identity",
    category: "logo",
    categoryLabel: "Logo Design",
    client: "Hijra Premium Dates & Nuts",
    year: "2025",
    image: "/Portfolio_page-0005.jpg",
    featured: true,
    metrics: "Selected for premium confectionery retail storefronts",
    description: "An elegant, traditional palm and dates emblem honoring Middle Eastern botanical heritage. Designed with balanced symmetry for luxury retail storefronts, gift packaging, and gourmet confectionery boxes.",
    deliverables: ["Palm Crest Mark", "Bespoke Arabic & English Typography", "Foil Stamping Guidelines", "Retail Signage"],
    tools: ["Adobe Illustrator", "Procreate", "Photoshop"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20want%20a%20logo%20like%20Hijra%20Dates%20and%20Nuts",
  },
  {
    id: "bullseye-marketing-logo",
    title: "Bullseye Marketing Agency",
    tagline: "Target Monogram & 3D Reception Signage",
    category: "logo",
    categoryLabel: "Logo Design",
    client: "Bullseye Marketing Group",
    year: "2025",
    image: "/Portfolio_page-0006.jpg",
    featured: false,
    metrics: "3D Acrylic Wall Signage & Full Corporate Identity",
    description: "A modern target bullseye logomark constructed inside letterform 'B'. Built for a high-growth marketing and media consultancy, emphasizing target precision, data results, and forward momentum.",
    deliverables: ["Isometric Brand Mark", "3D Acrylic Signage Specs", "Business Card System", "Digital Watermarks"],
    tools: ["Adobe Illustrator", "Cinema 4D", "Photoshop"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20a%20logo%20like%20Bullseye%20Marketing",
  },
  {
    id: "fryday-chicken-logo",
    title: "Fryday Fried Chicken",
    tagline: "Dynamic Rooster 'F' Lettermark & Fast Food Identity",
    category: "logo",
    categoryLabel: "Logo Design",
    client: "Fryday Fried Chicken",
    year: "2025",
    image: "/Portfolio_page-0007.jpg",
    featured: true,
    metrics: "Franchise Identity Rollout across Multiple Outlets",
    description: "A bold, energetic fast-casual restaurant logomark uniting the letter 'F' with a stylized rooster comb silhouette. Crafted with warm appetizing colors that trigger appetite and high highway visibility.",
    deliverables: ["Fast Food Lettermark", "Illuminated Lightbox Signs", "Colorway Variations", "Franchise Brand Standards"],
    tools: ["Adobe Illustrator", "Photoshop"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20want%20a%20restaurant%20logo%20like%20Fryday%20Chicken",
  },
  {
    id: "fryday-brandmarks-grid",
    title: "Fryday Iconography & Marks",
    tagline: "Comprehensive Sub-Marks, Colorways & Pattern Architecture",
    category: "logo",
    categoryLabel: "Logo Design",
    client: "Fryday Fried Chicken",
    year: "2025",
    image: "/Portfolio_page-0014.jpg",
    featured: false,
    metrics: "Complete Visual Symbol Architecture for Print & Digital",
    description: "Detailed secondary mark system, badge lockups, and social avatar marks for Fryday Fried Chicken. Created to provide cohesive brand expression across varied sizes from app icons to packaging tapes.",
    deliverables: ["Secondary Badges", "Sub-Brand Lockups", "Responsive Monograms", "Color Master Swatches"],
    tools: ["Adobe Illustrator", "Figma"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20brand%20iconography%20like%20Fryday",
  },
  {
    id: "dryvex-fleet-branding",
    title: "Dryvex Fleet Vehicle Branding",
    tagline: "Commercial Van Livery & On-Road Brand Identity",
    category: "logo",
    categoryLabel: "Logo Design",
    client: "Dryvex Mobile Car Wash",
    year: "2025",
    image: "/Portfolio_page-0031.jpg",
    featured: false,
    metrics: "High-Visibility Fleet Wraps Generating Daily Inquiries",
    description: "Custom full-wrap automotive graphic system for mobile car detailing vans. Incorporates dynamic speed ribbons, prominent logo placement, and legible contact information visible from highway distances.",
    deliverables: ["Full Vehicle Wrap Templates", "Die-Cut Vinyl Decals", "Reflective Fleet Lettering", "Mockup Renders"],
    tools: ["Adobe Illustrator", "Photoshop"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20vehicle%20branding%20like%20Dryvex",
  },
  {
    id: "dryvex-3d-emblem",
    title: "Dryvex Chrome Emblem System",
    tagline: "Photorealistic 3D Metallic Badge & Keycap Lockup",
    category: "logo",
    categoryLabel: "Logo Design",
    client: "Dryvex Automotive Group",
    year: "2026",
    image: "/Portfolio_page-0033.jpg",
    featured: false,
    metrics: "Rendered for Physical Die-Cast Badging & Merchandise",
    description: "Three-dimensional chrome and brushed metal rendering of the Dryvex emblem. Engineered for vehicle trunk badges, metallic keychain tags, and high-end automotive merchandise.",
    deliverables: ["3D CAD / STL Mesh", "High-Resolution Render Passes", "Emboss Depth Specifications"],
    tools: ["Cinema 4D", "Blender 3D", "Photoshop"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20am%20interested%20in%20a%203D%20badge%20like%20Dryvex",
  },

  // ==========================================
  // --- 2. BRANDING & PACKAGING CATEGORY ---
  // ==========================================
  {
    id: "fryday-storefront-branding",
    title: "Fryday Storefront & Retail Identity",
    tagline: "Architectural Signboard, Pylons & Interior Brand Application",
    category: "branding",
    categoryLabel: "Branding",
    client: "Fryday Fried Chicken",
    year: "2025",
    image: "/Portfolio_page-0013.jpg",
    featured: true,
    metrics: "End-to-End Environmental Branding for Fast Casual Diner",
    description: "Complete exterior and interior brand environment design for Fryday. Features illuminated channel lettering, roadside pylon displays, counter menu boards, and branded interior dining wall graphics.",
    deliverables: ["Storefront Elevation Plans", "Illuminated Signage Specs", "Wall Murals", "Directional Signage"],
    tools: ["Adobe Illustrator", "Photoshop", "AutoCAD"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20want%20storefront%20branding%20like%20Fryday",
  },
  {
    id: "fryday-packaging-system",
    title: "Fryday Fast Food Packaging Suite",
    tagline: "Eco Takeaway Boxes, Branded Cups & Fry Cartons",
    category: "branding",
    categoryLabel: "Branding",
    client: "Fryday Fried Chicken",
    year: "2025",
    image: "/Portfolio_page-0015.jpg",
    featured: true,
    metrics: "Food-Grade Biodegradable Custom Printed Packaging Line",
    description: "Turnkey packaging system featuring fried chicken family bucket designs, burger clamshells, French fry scoops, paper beverage cups, and greaseproof wrapping paper with custom repeating brand patterns.",
    deliverables: ["Bucket & Box Dielines", "Paper Cup Artwork", "Carry Bag Graphics", "Greaseproof Paper Patterns"],
    tools: ["Adobe Illustrator", "Photoshop", "InDesign"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20food%20packaging%20like%20Fryday",
  },
  {
    id: "fryday-staff-apparel",
    title: "Fryday Staff Apparel & Merch",
    tagline: "Uniforms, Aprons, Caps & Staff Merchandise System",
    category: "branding",
    categoryLabel: "Branding",
    client: "Fryday Fried Chicken",
    year: "2025",
    image: "/Portfolio_page-0016.jpg",
    featured: false,
    metrics: "Standardized Uniform System for Front & Kitchen Crew",
    description: "Designed professional branded culinary apparel including durable embroidered canvas aprons, staff polo shirts, snapback caps, and name badges for franchise consistency.",
    deliverables: ["Embroidery Vector Files", "Fabric & Colorway Specifications", "Merchandise Tech Packs"],
    tools: ["Adobe Illustrator", "Photoshop"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20staff%20apparel%20branding%20like%20Fryday",
  },
  {
    id: "hairy-luxe-cream-packaging",
    title: "Hairy Luxe Premium Cream Packaging",
    tagline: "Luxury Botanical Glass Jar & Dark Green Textured Outer Box",
    category: "branding",
    categoryLabel: "Branding",
    client: "Hairy Luxe Organics",
    year: "2025",
    image: "/Portfolio_page-0024.jpg",
    featured: true,
    metrics: "Luxury Cosmetic Packaging Distributed across Salons & Retail",
    description: "High-end cosmetic packaging design for organic hair care cream. Features gold foil typography, deep forest green tactile paper box, and frosted amber glass cosmetic jar with gold lid.",
    deliverables: ["Folding Carton Dieline", "Hot-Foil Stamping Plates", "Jar Silk-Screen Artwork", "Product 3D Mockups"],
    tools: ["Adobe Illustrator", "Photoshop", "Blender"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20want%20cosmetic%20packaging%20like%20Hairy%20Luxe",
  },
  {
    id: "hairy-luxe-complete-range",
    title: "Hairy Luxe Haircare Product Lineup",
    tagline: "Unified Identity for Shampoo, Conditioner, Oil & Cream",
    category: "branding",
    categoryLabel: "Branding",
    client: "Hairy Luxe Organics",
    year: "2025",
    image: "/Portfolio_page-0025.jpg",
    featured: true,
    metrics: "Full 4-SKU Retail Product Range Identity & Labeling",
    description: "Harmonious product line packaging spanning Hair Oil bottles, Deep Conditioner, Hair Serum, and Restorative Cream. Implements consistent typography, color coding, and luxury botanical iconography.",
    deliverables: ["Complete 4-SKU Label Suite", "Bottle Silk-Screen Printing", "Regulatory Ingredient Panels", "Point-of-Sale Displays"],
    tools: ["Adobe Illustrator", "Photoshop"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20want%20product%20line%20branding%20like%20Hairy%20Luxe",
  },
  {
    id: "avolio-sunscreen-packaging",
    title: "Avolio SPF 50 Aqua Gel Packaging",
    tagline: "Modern Skincare Tube Design & Clean Cosmetic Aesthetic",
    category: "branding",
    categoryLabel: "Branding",
    client: "Avolio Skincare Labs",
    year: "2026",
    image: "/Portfolio_page-0026.jpg",
    featured: true,
    metrics: "Dermatologist-Approved Skincare Retail Launch",
    description: "Fresh, clinical-yet-luxurious tube packaging design for SPF 50 Aqua Gel sunscreen. Emphasizes soothing aqua gradients, UV barrier iconography, and clean cosmetic minimalism.",
    deliverables: ["Laminated Tube Artwork", "UV Embossing Specifications", "Retail Display Box", "Marketing Render Assets"],
    tools: ["Adobe Illustrator", "Photoshop"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20skincare%20packaging%20like%20Avolio%20Sunscreen",
  },
  {
    id: "dryvex-brand-guidelines",
    title: "Dryvex Visual Identity System & Guidelines",
    tagline: "Comprehensive Geometry, Spacing & Brand Architecture Book",
    category: "branding",
    categoryLabel: "Branding",
    client: "Dryvex Car Wash",
    year: "2025",
    image: "/Portfolio_page-0009.jpg",
    featured: false,
    metrics: "Corporate Identity Manual Guiding Multi-Location Franchise",
    description: "A comprehensive brand identity specification manual detailing construction grids, clear zones, minimum reproduction sizes, and forbidden usage guidelines for corporate consistency.",
    deliverables: ["Brand Manual PDF", "Vector Construction Grids", "Clearance Rules", "Franchise Distribution Kit"],
    tools: ["Adobe Illustrator", "InDesign"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20a%20brand%20identity%20guide%20like%20Dryvex",
  },
  {
    id: "dryvex-color-system",
    title: "Dryvex Color Spectrum & Palette System",
    tagline: "Amber Glow, Red Berry & Peach Beige Color Hierarchy",
    category: "branding",
    categoryLabel: "Branding",
    client: "Dryvex Car Wash",
    year: "2025",
    image: "/Portfolio_page-0010.jpg",
    featured: false,
    metrics: "Standardized CMYK, Pantone, RGB & Hex Specifications",
    description: "Vibrant automotive color hierarchy engineered with Amber Glow (#F4A91E), Red Berry (#CF232A), and Peach Beige (#F8E7C9). Built to ensure chromatic fidelity across fleet vinyls, signage, and screen displays.",
    deliverables: ["Pantone Swatch Match", "CMYK Print Formulas", "Digital Contrast Ratios", "Accessibility Testing"],
    tools: ["Adobe Illustrator", "InDesign"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20want%20a%20color%20palette%20system%20like%20Dryvex",
  },
  {
    id: "dryvex-corporate-stationery",
    title: "Dryvex Corporate Stationery Suite",
    tagline: "Business Cards, Letterhead, Folders & Envelopes",
    category: "branding",
    categoryLabel: "Branding",
    client: "Dryvex Car Wash",
    year: "2025",
    image: "/Portfolio_page-0011.jpg",
    featured: false,
    metrics: "Executive Corporate Collateral & Print Finishing Suite",
    description: "Complete corporate print identity featuring luxury cotton paper business cards with spot UV finish, executive letterheads, invoice templates, and branded presentation folders.",
    deliverables: ["Business Card System", "Letterhead & Invoicing Templates", "Presentation Folder Dielines", "Envelope Artworks"],
    tools: ["Adobe InDesign", "Photoshop", "Illustrator"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20corporate%20stationery%20like%20Dryvex",
  },
  {
    id: "dryvex-service-collateral",
    title: "Dryvex Service & Marketing Collateral",
    tagline: "'We Wash Your Car' Promotional Loyalty Cards & Flyers",
    category: "branding",
    categoryLabel: "Branding",
    client: "Dryvex Car Wash",
    year: "2025",
    image: "/Portfolio_page-0012.jpg",
    featured: false,
    metrics: "High-Response Customer Retention & Loyalty Card Campaign",
    description: "Customer loyalty cards, promotional wash vouchers, rearview mirror service tags, and counter brochures designed to drive repeat customer bookings and membership signups.",
    deliverables: ["Loyalty Stamp Cards", "Mirror Hangtags", "Tri-Fold Service Menus", "Promo Postcards"],
    tools: ["Adobe Illustrator", "InDesign"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20loyalty%20collateral%20like%20Dryvex",
  },

  // ==========================================
  // --- 3. POSTER & BILLBOARD CATEGORY ---
  // ==========================================
  {
    id: "real-madrid-sports-poster",
    title: "Real Madrid 'Better' Sports Poster",
    tagline: "Vintage Halftone Retro Sports Graphic & Player Collage",
    category: "poster",
    categoryLabel: "Poster Design",
    client: "Sports Graphic Art Series",
    year: "2025",
    image: "/Portfolio_page-0028.jpg",
    featured: true,
    metrics: "Viral Sports Art Print with 20,000+ Social Engagements",
    description: "Dynamic sports tribute poster celebrating Real Madrid stars including Jude Bellingham, Vinicius Jr, and Luka Modric. Features vintage newspaper halftone textures, bold distressed typography, and retro paper grain.",
    deliverables: ["A2 Archival Fine Art Prints", "Digital Wallpaper Suite", "Social Poster Releases"],
    tools: ["Adobe Photoshop", "Illustrator", "Camera Raw"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20love%20the%20Real%20Madrid%20sports%20poster%20style",
  },
  {
    id: "almas-hospital-billboard",
    title: "Almas Hospital Highway Billboard",
    tagline: "'Let Every Heart Beat With Health' Large-Format Outdoor Ad",
    category: "poster",
    categoryLabel: "Poster Design",
    client: "Almas Hospital & Healthcare",
    year: "2025",
    image: "/Portfolio_page-0032.jpg",
    featured: true,
    metrics: "Highway Billboards Viewed by Over 100,000 Commuters Daily",
    description: "Large-scale roadside highway billboard campaign promoting advanced cardiac care and healthcare services. High-contrast typography and empathetic imagery crafted for instant recognition at highway speeds.",
    deliverables: ["Large-Format Outdoor Billboard", "Bus Shelter Graphic Prints", "Print Proof Approval Files"],
    tools: ["Adobe Photoshop", "Illustrator", "Large-Format Prepress"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20a%20highway%20billboard%20like%20Almas%20Hospital",
  },
  {
    id: "msm-balavedi-youth-poster",
    title: "MSM Balavedi Youth Conference",
    tagline: "'Talk, Learn, Lead, Play, Repeat' Event Graphic Poster",
    category: "poster",
    categoryLabel: "Poster Design",
    client: "MSM Kerala Youth Movement",
    year: "2026",
    image: "/whatsapp-msm-balavedi.jpeg",
    featured: true,
    metrics: "Over 5,000 Youth Attendees Registered via Event Campaign",
    description: "Vibrant, high-energy event poster design for the Calicut youth conference. Features bold modern layout, engaging iconography, and clear schedule typography for maximum youth engagement.",
    deliverables: ["Conference Posters (A1/A3)", "Social Announcement Banners", "Stage Backdrop Display", "Delegate Badges"],
    tools: ["Adobe Photoshop", "Illustrator"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20an%20event%20poster%20like%20MSM%20Balavedi",
  },
  {
    id: "msm-student-confluence",
    title: "MSM Student Confluence Poster",
    tagline: "Generations & Milestones Student Conclave Visual Identity",
    category: "poster",
    categoryLabel: "Poster Design",
    client: "MSM Kozhikode District",
    year: "2026",
    image: "/whatsapp-msm-confluence.jpeg",
    featured: false,
    metrics: "State-Wide Student Engagement & Campus Campaign",
    description: "Dynamic educational confluence poster incorporating deep blue gradients, structured event information, guest speakers list, and QR code integration for instant registrations.",
    deliverables: ["Campus Notice Board Posters", "Digital Flyers", "Social Story Formats"],
    tools: ["Adobe Photoshop", "Illustrator"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20want%20a%20student%20confluence%20poster%20like%20MSM",
  },
  {
    id: "family-meet-poster",
    title: "Family Meet 2026 Celebration Poster",
    tagline: "Warm Community Gathering & Event Visual Design",
    category: "poster",
    categoryLabel: "Poster Design",
    client: "Community Cultural Committee",
    year: "2026",
    image: "/whatsapp-family-meet-2026.jpeg",
    featured: false,
    metrics: "Full Attendance at Annual Community Gathering",
    description: "Heartwarming celebration poster created for the 2026 family assembly. Clean layout with festive visual elements and welcoming typography to bring families together.",
    deliverables: ["Printable Event Poster", "Digital Invitations", "WhatsApp Broadcast Creatives"],
    tools: ["Adobe Photoshop", "Illustrator"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20a%20family%20meet%20poster%20design",
  },
  {
    id: "msm-cultural-fest-poster",
    title: "MSM State Youth Cultural Festival",
    tagline: "State-Level Youth Cultural & Literary Convention Poster",
    category: "poster",
    categoryLabel: "Poster Design",
    client: "MSM State Committee",
    year: "2026",
    image: "/whatsapp-msm-cultural-fest.jpeg",
    featured: false,
    metrics: "Statewide Cultural Event Attracting Hundreds of Talents",
    description: "Grand cultural convention poster celebrating arts, literature, and youth leadership. Designed with majestic typography, intricate Islamic artistic motifs, and clear competitive guidelines.",
    deliverables: ["Official Festival Poster", "Certificates & Medals Design", "Press Release Graphics"],
    tools: ["Adobe Photoshop", "Illustrator"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20a%20cultural%20festival%20poster%20design",
  },

  // ==========================================
  // --- 4. WEBSITE CATEGORY ---
  // ==========================================
  {
    id: "groweo-digital-website",
    title: "Groweo Digital Agency Corporate UI",
    tagline: "Modern Agency Website Collateral, UI Design & Multi-Fold Suite",
    category: "website",
    categoryLabel: "Website",
    client: "Groweo Digital Solutions",
    year: "2025",
    image: "/Portfolio_page-0029.jpg",
    featured: true,
    metrics: "Corporate Web Platform & Collateral Boosting Lead Generation",
    description: "Full web UI design and corporate collateral for groweo.com. Features clean service tier grids, conversion-focused hero layout, client testimonials, and branded multi-fold marketing collateral.",
    deliverables: ["Figma UI Design System", "Responsive Web Layouts", "Corporate Presentation Folio", "Service Showcase Pages"],
    tools: ["Figma", "Adobe Illustrator", "Photoshop", "Next.js"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20want%20a%20corporate%20website%20like%20Groweo",
  },
  {
    id: "lecygnex-digital-portal",
    title: "Le Cygnex Digital Agency Platform",
    tagline: "Modern Web Presence & Interactive Service Experience",
    category: "website",
    categoryLabel: "Website",
    client: "Le Cygnex Digital Agency",
    year: "2026",
    image: "/whatsapp-lecygnex-portal.jpeg",
    featured: true,
    metrics: "Flagship Corporate Platform Driving Client Onboarding",
    description: "The official web presence for Le Cygnex Digital Agency. Engineered with clean typography, dynamic project showcase, sleek modern layout, and interactive WhatsApp and email booking funnels.",
    deliverables: ["Full-Stack Web Architecture", "High-Converting Hero Section", "Interactive Work Portfolio", "Client Inquiry Engine"],
    tools: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20a%20digital%20agency%20website%20like%20Le%20Cygnex",
  },
  {
    id: "lecygnex-services-showcase",
    title: "Le Cygnex Full-Stack Digital Services",
    tagline: "Web Development, SEO, Branding & Content Solutions UI",
    category: "website",
    categoryLabel: "Website",
    client: "Le Cygnex Digital Agency",
    year: "2026",
    image: "/whatsapp-lecygnex-services.jpeg",
    featured: false,
    metrics: "Comprehensive Digital Solutions Suite with High CTR",
    description: "Interactive digital solutions interface outlining web development, search engine optimization, graphic design, and content marketing services. Designed with high visual hierarchy and responsive cards.",
    deliverables: ["Service Breakdown Cards", "Interactive Feature Grids", "Client ROI Calculator UI"],
    tools: ["Next.js", "Figma", "Tailwind CSS"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20a%20services%20showcase%20page%20like%20Le%20Cygnex",
  },

  // ==========================================
  // --- 5. SOCIAL MEDIA CATEGORY ---
  // ==========================================
  {
    id: "the-library-cafe-promo",
    title: "The Library Cafe 'Spice Up Your Life'",
    tagline: "20% Off Restaurant Promo Creative & Food Social Campaign",
    category: "social-media",
    categoryLabel: "Social Media",
    client: "The Library Cafe & Restaurant",
    year: "2025",
    image: "/Portfolio_page-0021.jpg",
    featured: true,
    metrics: "+65% Increase in Table Reservations during Promo Window",
    description: "Mouth-watering culinary social media creative promoting a 20% discount offer. Features cinematic food photography lighting, bold appetizing typography, and urgency badge.",
    deliverables: ["Instagram Feed Post (1:1)", "Instagram Stories (9:16)", "Table Tent Cards", "Digital Menu Banner"],
    tools: ["Adobe Photoshop", "Lightroom"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20want%20restaurant%20social%20creatives%20like%20The%20Library%20Cafe",
  },
  {
    id: "nayara-energy-truelink",
    title: "Nayara Energy x True Link Qatar",
    tagline: "1500+ Nayara Petrol Pumps Industrial Supply Campaign",
    category: "social-media",
    categoryLabel: "Social Media",
    client: "True Link Trading Qatar",
    year: "2025",
    image: "/Portfolio_page-0018.jpg",
    featured: true,
    metrics: "Corporate Supply Campaign Reaching Petrochemical Clients",
    description: "B2B commercial campaign creative highlighting True Link Qatar's partnership powering 1500+ Nayara fuel retail stations with printing and billing consumables.",
    deliverables: ["B2B Social Campaign Assets", "Corporate Announcement Banners", "WhatsApp Marketing Cards"],
    tools: ["Adobe Photoshop", "Illustrator"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20want%20B2B%20social%20creatives%20like%20True%20Link%20x%20Nayara",
  },
  {
    id: "truelink-office-supplies",
    title: "True Link Qatar Office Supplies Campaign",
    tagline: "Budget Office Printing & Hardware Instagram Ad Series",
    category: "social-media",
    categoryLabel: "Social Media",
    client: "True Link Trading Qatar",
    year: "2025",
    image: "/Portfolio_page-0019.jpg",
    featured: false,
    metrics: "High-CTR Social Ads Generating Bulk Business Orders in Doha",
    description: "Engaging commercial social media advertisements showcasing heavy-duty barcode printers, thermal paper rolls, and POS accessories for retail businesses in Qatar.",
    deliverables: ["Product Carousel Ads", "Story Ads with Direct WhatsApp Links", "Promotional Price Badges"],
    tools: ["Adobe Photoshop", "Illustrator"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20product%20ad%20creatives%20like%20True%20Link%20Qatar",
  },
  {
    id: "qatar-national-day",
    title: "Qatar National Day Dec 18 Creative",
    tagline: "Commemorative Maroon & White Festive Social Tribute",
    category: "social-media",
    categoryLabel: "Social Media",
    client: "True Link Trading Qatar",
    year: "2025",
    image: "/Portfolio_page-0020.jpg",
    featured: false,
    metrics: "High Community Engagement Across Qatar Corporate Networks",
    description: "Culturally rich commemorative social creative honoring Qatar National Day (Dec 18). Features traditional architectural silhouettes, national flag maroon hues, and refined bilingual calligraphy.",
    deliverables: ["National Day Feed Graphics", "Story Greeting Cards", "Email Newsletter Header"],
    tools: ["Adobe Photoshop", "Illustrator"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20holiday%20greeting%20designs%20like%20Qatar%20National%20Day",
  },
  {
    id: "truelink-newyear-luxury",
    title: "True Link New Year & Luxury Furniture",
    tagline: "Multi-Slide Instagram Carousel & Luxury Furniture Campaign",
    category: "social-media",
    categoryLabel: "Social Media",
    client: "True Link Trading Qatar",
    year: "2025",
    image: "/Portfolio_page-0022.jpg",
    featured: false,
    metrics: "+180% Engagement on New Year Social Carousel",
    description: "Elegant multi-slide New Year greeting and luxury office furniture campaign. Pairs premium warm wood aesthetics with minimalist festive design and corporate holiday greetings.",
    deliverables: ["Instagram Carousel (10 slides)", "Story Highlights Icons", "Customer Greeting Cards"],
    tools: ["Adobe Photoshop", "Illustrator"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20Instagram%20carousel%20designs%20like%20True%20Link",
  },
  {
    id: "lecygnex-audience-scrolling",
    title: "Le Cygnex 'Your Audience Is Scrolling'",
    tagline: "High-Converting Social Media Ad Creative & Agency Campaign",
    category: "social-media",
    categoryLabel: "Social Media",
    client: "Le Cygnex Digital Agency",
    year: "2026",
    image: "/whatsapp-audience-scrolling.jpeg",
    featured: true,
    metrics: "3.4x Higher Click-Through Rate Compared to Industry Average",
    description: "Attention-grabbing social ad creative targeting business owners: 'Your audience is already scrolling. Are they scrolling past you?' Designed to drive agency consultations and client acquisition.",
    deliverables: ["Instagram Ad Creatives", "LinkedIn Feed Banners", "Interactive Paid Ad Campaign"],
    tools: ["Adobe Photoshop", "Illustrator"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20want%20high-converting%20social%20creatives%20like%20Le%20Cygnex",
  },
  {
    id: "lecygnex-agency-banner",
    title: "Le Cygnex Digital Agency Brand Banner",
    tagline: "Comprehensive Services & Brand Positioning Graphic",
    category: "social-media",
    categoryLabel: "Social Media",
    client: "Le Cygnex Digital Agency",
    year: "2026",
    image: "/whatsapp-lecygnex-banner.jpeg",
    featured: false,
    metrics: "Official Brand Collateral Displayed Across Social Channels",
    description: "Master banner highlighting Le Cygnex's full service offerings: Digital Marketing, Branding, Web Development, SEO, and Content Creation with bold typography and direct contact details.",
    deliverables: ["Profile Cover Banners", "Social Media Headers", "Brochure Inserts"],
    tools: ["Adobe Photoshop", "Illustrator"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20an%20agency%20brand%20banner%20like%20Le%20Cygnex",
  },
  {
    id: "independence-day-creative",
    title: "Independence Day Social Tribute",
    tagline: "August 15 Patriotic Social Campaign & Festive Design",
    category: "social-media",
    categoryLabel: "Social Media",
    client: "Client Community Campaign",
    year: "2025",
    image: "/whatsapp-independence-day.jpeg",
    featured: false,
    metrics: "Wide Viral Reach across WhatsApp & Social Channels",
    description: "Inspiring patriotic social creative celebrating Independence Day with tricolor artistic typography, cultural monument silhouettes, and celebratory message of freedom and pride.",
    deliverables: ["Festival Feed Post", "WhatsApp Status Creative", "Digital Flyer"],
    tools: ["Adobe Photoshop", "Illustrator"],
    liveUrl: "https://wa.me/919074063277?text=Hi%2C%20I%20need%20festival%20creatives%20like%20Independence%20Day",
  },
];
